name: ipfinder
description: Official Dart client library for IPfinder.
    - IP address details.
    - ASN details.
    - Firewall by supported formats details.
    - IP Address Ranges by the Organization name details.
    - service status details.
    - Get Domain IP.
    - Get Domain IP history.
    - Get list Domain By ASN, Country,Ranges.
version: 1.0.1
author: Mohamed Ben rebia <mohamed@ipfinder.io>
homepage: https://ipfinder.io
repository: https://github.com/ipfinder-io/ip-finder-dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+2
  # flutter:
  #   sdk: flutter

dev_dependencies:
  test: ^1.6.10
