name: ipfinder
description: Official Dart client library for IPfinder.
version: 1.0.0
author: Mohamed Ben rebia <mohamed@ipfinder.io>
homepage: https://ipfinder.io/
repository: https://github.com/ipfinder-io/ip-finder-dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+2
  # flutter:
  #   sdk: flutter

dev_dependencies:
  test: ^1.6.10
